#!/bin/bash

set -eu

function tag_branch {
  docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:$1"
  docker push "${DOCKER_REPO}:$1"
}

# For unofficial documentation, see: https://docs.docker.com/docker-cloud/builds/advanced/
# Available variables:
# - `SOURCE_BRANCH`: the name of the branch or the tag that is currently being tested.
# - `SOURCE_COMMIT`: the SHA1 hash of the commit being tested.
# - `COMMIT_MSG`: the message from the commit being tested and built.
# - `DOCKER_REPO`: the name of the Docker repository being built.
# - `CACHE_TAG`: the Docker repository tag being built.
# - `IMAGE_NAME`: the name and tag of the Docker repository being built. (This variable is a combination of `DOCKER_REPO`:`CACHE_TAG`.)
#
# SHA_COMMIT=${SOURCE_COMMIT:0:8}
echo "Image ${CACHE_TAG} built, tagging..."
if [[ "${CACHE_TAG}" == "stable" ]]; then
  CHANNEL_VERSION="$(curl -sSL "http://www.ubnt.com/downloads/unifi/debian/dists/${CACHE_TAG}/ubiquiti/binary-armhf/Packages.gz" \
    | zgrep Version | sed -rn 's/Version: ([[:digit:]].[[:digit:]].[[:digit:]]+)-.*/\1/p')"

  echo "Adding 'latest' and '${CHANNEL_VERSION}' tags"

  tag_branch "latest"
  tag_branch "${CHANNEL_VERSION}"
elif [[ "${CACHE_TAG}" == "oldstable" ]]; then
  CHANNEL_VERSION="$(curl -sSL "http://www.ubnt.com/downloads/unifi/debian/dists/${CACHE_TAG}/ubiquiti/binary-armhf/Packages.gz" \
    | zgrep Version | sed -rn 's/Version: ([[:digit:]].[[:digit:]].[[:digit:]]+)-.*/\1/p')"

  tag_branch "${CHANNEL_VERSION}"
fi
